import Box from "./component/box/box.component";
import React from "react";


function App() {
  return (
    <div>      
      <Box />
<p>Lorem ipsum dolor sit amet. Sit nisi officia rem voluptates suscipit et culpa consequatur qui porro laborum. Sit culpa explicabo a explicabo voluptas non libero dolores aut neque voluptate et voluptatum deserunt. </p><p>Vel tempora illo in vero aspernatur in eius error et odit praesentium quo perspiciatis natus ut dolorem quia. Et cumque totam sed aliquid enim est quia quam est molestias aspernatur et quia accusantium ab blanditiis quod. In possimus voluptatum nam recusandae vitae id unde iste in aspernatur neque aut natus quia et temporibus cupiditate sit rerum perferendis. Et optio unde rem itaque nisi non quaerat iusto et dolores rerum ut corrupti soluta ab galisum quis. </p><p>Et veritatis internos ab voluptas molestias sit voluptatem velit. Et quisquam minima et quia molestias et suscipit sint aut totam consectetur qui cupiditate quaerat et sint voluptas et quia rerum. Sed tempore repellendus sed labore ratione sit dolore error et voluptatum iure est doloribus nobis eum ducimus vitae aut voluptatum architecto. A voluptatem aperiam aut dolor impedit vel commodi pariatur aut deserunt repellendus ut deleniti voluptatum qui distinctio fugit. </p>
<p>Lorem ipsum dolor sit amet. Sit nisi officia rem voluptates suscipit et culpa consequatur qui porro laborum. Sit culpa explicabo a explicabo voluptas non libero dolores aut neque voluptate et voluptatum deserunt. </p><p>Vel tempora illo in vero aspernatur in eius error et odit praesentium quo perspiciatis natus ut dolorem quia. Et cumque totam sed aliquid enim est quia quam est molestias aspernatur et quia accusantium ab blanditiis quod. In possimus voluptatum nam recusandae vitae id unde iste in aspernatur neque aut natus quia et temporibus cupiditate sit rerum perferendis. Et optio unde rem itaque nisi non quaerat iusto et dolores rerum ut corrupti soluta ab galisum quis. </p><p>Et veritatis internos ab voluptas molestias sit voluptatem velit. Et quisquam minima et quia molestias et suscipit sint aut totam consectetur qui cupiditate quaerat et sint voluptas et quia rerum. Sed tempore repellendus sed labore ratione sit dolore error et voluptatum iure est doloribus nobis eum ducimus vitae aut voluptatum architecto. A voluptatem aperiam aut dolor impedit vel commodi pariatur aut deserunt repellendus ut deleniti voluptatum qui distinctio fugit. </p>
<p>Lorem ipsum dolor sit amet. Sit nisi officia rem voluptates suscipit et culpa consequatur qui porro laborum. Sit culpa explicabo a explicabo voluptas non libero dolores aut neque voluptate et voluptatum deserunt. </p><p>Vel tempora illo in vero aspernatur in eius error et odit praesentium quo perspiciatis natus ut dolorem quia. Et cumque totam sed aliquid enim est quia quam est molestias aspernatur et quia accusantium ab blanditiis quod. In possimus voluptatum nam recusandae vitae id unde iste in aspernatur neque aut natus quia et temporibus cupiditate sit rerum perferendis. Et optio unde rem itaque nisi non quaerat iusto et dolores rerum ut corrupti soluta ab galisum quis. </p><p>Et veritatis internos ab voluptas molestias sit voluptatem velit. Et quisquam minima et quia molestias et suscipit sint aut totam consectetur qui cupiditate quaerat et sint voluptas et quia rerum. Sed tempore repellendus sed labore ratione sit dolore error et voluptatum iure est doloribus nobis eum ducimus vitae aut voluptatum architecto. A voluptatem aperiam aut dolor impedit vel commodi pariatur aut deserunt repellendus ut deleniti voluptatum qui distinctio fugit. </p>
<p>Lorem ipsum dolor sit amet. Sit nisi officia rem voluptates suscipit et culpa consequatur qui porro laborum. Sit culpa explicabo a explicabo voluptas non libero dolores aut neque voluptate et voluptatum deserunt. </p><p>Vel tempora illo in vero aspernatur in eius error et odit praesentium quo perspiciatis natus ut dolorem quia. Et cumque totam sed aliquid enim est quia quam est molestias aspernatur et quia accusantium ab blanditiis quod. In possimus voluptatum nam recusandae vitae id unde iste in aspernatur neque aut natus quia et temporibus cupiditate sit rerum perferendis. Et optio unde rem itaque nisi non quaerat iusto et dolores rerum ut corrupti soluta ab galisum quis. </p><p>Et veritatis internos ab voluptas molestias sit voluptatem velit. Et quisquam minima et quia molestias et suscipit sint aut totam consectetur qui cupiditate quaerat et sint voluptas et quia rerum. Sed tempore repellendus sed labore ratione sit dolore error et voluptatum iure est doloribus nobis eum ducimus vitae aut voluptatum architecto. A voluptatem aperiam aut dolor impedit vel commodi pariatur aut deserunt repellendus ut deleniti voluptatum qui distinctio fugit. </p>
<p>Lorem ipsum dolor sit amet. Sit nisi officia rem voluptates suscipit et culpa consequatur qui porro laborum. Sit culpa explicabo a explicabo voluptas non libero dolores aut neque voluptate et voluptatum deserunt. </p><p>Vel tempora illo in vero aspernatur in eius error et odit praesentium quo perspiciatis natus ut dolorem quia. Et cumque totam sed aliquid enim est quia quam est molestias aspernatur et quia accusantium ab blanditiis quod. In possimus voluptatum nam recusandae vitae id unde iste in aspernatur neque aut natus quia et temporibus cupiditate sit rerum perferendis. Et optio unde rem itaque nisi non quaerat iusto et dolores rerum ut corrupti soluta ab galisum quis. </p><p>Et veritatis internos ab voluptas molestias sit voluptatem velit. Et quisquam minima et quia molestias et suscipit sint aut totam consectetur qui cupiditate quaerat et sint voluptas et quia rerum. Sed tempore repellendus sed labore ratione sit dolore error et voluptatum iure est doloribus nobis eum ducimus vitae aut voluptatum architecto. A voluptatem aperiam aut dolor impedit vel commodi pariatur aut deserunt repellendus ut deleniti voluptatum qui distinctio fugit. </p>
<p>Lorem ipsum dolor sit amet. Sit nisi officia rem voluptates suscipit et culpa consequatur qui porro laborum. Sit culpa explicabo a explicabo voluptas non libero dolores aut neque voluptate et voluptatum deserunt. </p><p>Vel tempora illo in vero aspernatur in eius error et odit praesentium quo perspiciatis natus ut dolorem quia. Et cumque totam sed aliquid enim est quia quam est molestias aspernatur et quia accusantium ab blanditiis quod. In possimus voluptatum nam recusandae vitae id unde iste in aspernatur neque aut natus quia et temporibus cupiditate sit rerum perferendis. Et optio unde rem itaque nisi non quaerat iusto et dolores rerum ut corrupti soluta ab galisum quis. </p><p>Et veritatis internos ab voluptas molestias sit voluptatem velit. Et quisquam minima et quia molestias et suscipit sint aut totam consectetur qui cupiditate quaerat et sint voluptas et quia rerum. Sed tempore repellendus sed labore ratione sit dolore error et voluptatum iure est doloribus nobis eum ducimus vitae aut voluptatum architecto. A voluptatem aperiam aut dolor impedit vel commodi pariatur aut deserunt repellendus ut deleniti voluptatum qui distinctio fugit. </p>


    </div>
  )
   
  
}

export default App;
